org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true

version_code=11520
version_name=1.1.5.2

bugly_id=
mst_id=

#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=7890
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=7890
